sudo: required
language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo apt-get update -qq

install: 
  # C++17
  - sudo apt-get install -qq g++-7 clang-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

os: linux
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-7
      packages:
        - clang-7
        - libstdc++-7-dev

compiler:
  - g++
  - clang

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./CourseDashboard-ut
